-- =============================================================================
-- Pays ISO 3166-1 — FICHIER GÉNÉRÉ par db/scripts/generate-reference-seed.ts.
-- Ne pas modifier à la main. 250 pays et territoires.
-- Aucun pays n'est ouvert (can_send / can_receive = false). La relance ne
-- modifie jamais risk_level, can_send ni can_receive.
-- =============================================================================
INSERT INTO ref.countries (alpha2, alpha3, numeric_code, name_en, name_fr, continent, calling_code, default_currency) VALUES
    ('AD', 'AND', '020', 'Andorra', 'Andorre', 'EU', '376', 'EUR'),
    ('AE', 'ARE', '784', 'United Arab Emirates', 'Émirats Arabes Unis', 'AS', '971', 'AED'),
    ('AF', 'AFG', '004', 'Afghanistan', 'Afghanistan', 'AS', '93', 'AFN'),
    ('AG', 'ATG', '028', 'Antigua and Barbuda', 'Antigua-et-Barbuda', 'NA', '1', 'XCD'),
    ('AI', 'AIA', '660', 'Anguilla', 'Anguilla', 'NA', '1', 'XCD'),
    ('AL', 'ALB', '008', 'Albania', 'Albanie', 'EU', '355', 'ALL'),
    ('AM', 'ARM', '051', 'Armenia', 'Arménie', 'AS', '374', 'AMD'),
    ('AO', 'AGO', '024', 'Angola', 'Angola', 'AF', '244', 'AOA'),
    ('AQ', 'ATA', '010', 'Antarctica', 'Antarctique', 'AN', '672', 'USD'),
    ('AR', 'ARG', '032', 'Argentina', 'Argentine', 'SA', '54', 'ARS'),
    ('AS', 'ASM', '016', 'American Samoa', 'Samoa américaines', 'OC', '1', 'USD'),
    ('AT', 'AUT', '040', 'Austria', 'Autriche', 'EU', '43', 'EUR'),
    ('AU', 'AUS', '036', 'Australia', 'Australie', 'OC', '61', 'AUD'),
    ('AW', 'ABW', '533', 'Aruba', 'Aruba', 'NA', '297', 'AWG'),
    ('AX', 'ALA', '248', 'Åland Islands', 'Åland', 'EU', '358', 'EUR'),
    ('AZ', 'AZE', '031', 'Azerbaijan', 'Azerbaïdjan', 'AS', '994', 'AZN'),
    ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'EU', '387', 'BAM'),
    ('BB', 'BRB', '052', 'Barbados', 'Barbade', 'NA', '1', 'BBD'),
    ('BD', 'BGD', '050', 'Bangladesh', 'Bangladesh', 'AS', '880', 'BDT'),
    ('BE', 'BEL', '056', 'Belgium', 'Belgique', 'EU', '32', 'EUR'),
    ('BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'AF', '226', 'XOF'),
    ('BG', 'BGR', '100', 'Bulgaria', 'Bulgarie', 'EU', '359', 'EUR'),
    ('BH', 'BHR', '048', 'Bahrain', 'Bahreïn', 'AS', '973', 'BHD'),
    ('BI', 'BDI', '108', 'Burundi', 'Burundi', 'AF', '257', 'BIF'),
    ('BJ', 'BEN', '204', 'Benin', 'Bénin', 'AF', '229', 'XOF'),
    ('BL', 'BLM', '652', 'Saint Barthélemy', 'Saint-Barthélemy', 'NA', '590', 'EUR'),
    ('BM', 'BMU', '060', 'Bermuda', 'Bermudes', 'NA', '1', 'BMD'),
    ('BN', 'BRN', '096', 'Brunei Darussalam', 'Brunei Darussalam', 'AS', '673', 'BND'),
    ('BO', 'BOL', '068', 'Bolivia', 'Bolivie', 'SA', '591', 'BOB'),
    ('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Saint-Eustache et Saba', 'NA', '599', 'USD'),
    ('BR', 'BRA', '076', 'Brazil', 'Brésil', 'SA', '55', 'BRL'),
    ('BS', 'BHS', '044', 'Bahamas', 'Bahamas', 'NA', '1', 'BSD'),
    ('BT', 'BTN', '064', 'Bhutan', 'Bhoutan', 'AS', '975', 'BTN'),
    ('BV', 'BVT', '074', 'Bouvet Island', 'Île Bouvet', 'AN', '47', 'NOK'),
    ('BW', 'BWA', '072', 'Botswana', 'Botswana', 'AF', '267', 'BWP'),
    ('BY', 'BLR', '112', 'Belarus', 'Biélorussie', 'EU', '375', 'BYN'),
    ('BZ', 'BLZ', '084', 'Belize', 'Belize', 'NA', '501', 'BZD'),
    ('CA', 'CAN', '124', 'Canada', 'Canada', 'NA', '1', 'CAD'),
    ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'Îles Cocos', 'AS', '61', 'AUD'),
    ('CD', 'COD', '180', 'Democratic Republic of the Congo', 'République démocratique du Congo', 'AF', '243', 'CDF'),
    ('CF', 'CAF', '140', 'Central African Republic', 'République Centrafricaine', 'AF', '236', 'XAF'),
    ('CG', 'COG', '178', 'Republic of the Congo', 'République du Congo', 'AF', '242', 'XAF'),
    ('CH', 'CHE', '756', 'Switzerland', 'Suisse', 'EU', '41', 'CHF'),
    ('CI', 'CIV', '384', 'Cote d''Ivoire', 'Côte-d''Ivoire', 'AF', '225', 'XOF'),
    ('CK', 'COK', '184', 'Cook Islands', 'Îles Cook', 'OC', '682', 'NZD'),
    ('CL', 'CHL', '152', 'Chile', 'Chili', 'SA', '56', 'CLP'),
    ('CM', 'CMR', '120', 'Cameroon', 'Cameroun', 'AF', '237', 'XAF'),
    ('CN', 'CHN', '156', 'People''s Republic of China', 'Chine', 'AS', '86', 'CNY'),
    ('CO', 'COL', '170', 'Colombia', 'Colombie', 'SA', '57', 'COP'),
    ('CR', 'CRI', '188', 'Costa Rica', 'Costa Rica', 'NA', '506', 'CRC'),
    ('CU', 'CUB', '192', 'Cuba', 'Cuba', 'NA', '53', 'CUP'),
    ('CV', 'CPV', '132', 'Cape Verde', 'Cap-Vert', 'AF', '238', 'CVE'),
    ('CW', 'CUW', '531', 'Curaçao', 'Curaçao', 'NA', '599', 'XCG'),
    ('CX', 'CXR', '162', 'Christmas Island', 'Île Christmas', 'AS', '61', 'AUD'),
    ('CY', 'CYP', '196', 'Cyprus', 'Chypre', 'EU', '357', 'EUR'),
    ('CZ', 'CZE', '203', 'Czech Republic', 'République Tchèque', 'EU', '420', 'CZK'),
    ('DE', 'DEU', '276', 'Germany', 'Allemagne', 'EU', '49', 'EUR'),
    ('DJ', 'DJI', '262', 'Djibouti', 'Djibouti', 'AF', '253', 'DJF'),
    ('DK', 'DNK', '208', 'Denmark', 'Danemark', 'EU', '45', 'DKK'),
    ('DM', 'DMA', '212', 'Dominica', 'Dominique', 'NA', '1', 'XCD'),
    ('DO', 'DOM', '214', 'Dominican Republic', 'République Dominicaine', 'NA', '1', 'DOP'),
    ('DZ', 'DZA', '012', 'Algeria', 'Algérie', 'AF', '213', 'DZD'),
    ('EC', 'ECU', '218', 'Ecuador', 'Équateur', 'SA', '593', 'USD'),
    ('EE', 'EST', '233', 'Estonia', 'Estonie', 'EU', '372', 'EUR'),
    ('EG', 'EGY', '818', 'Egypt', 'Égypte', 'AF', '20', 'EGP'),
    ('EH', 'ESH', '732', 'Western Sahara', 'Sahara occidental', 'AF', '212', 'MAD'),
    ('ER', 'ERI', '232', 'Eritrea', 'Érythrée', 'AF', '291', 'ERN'),
    ('ES', 'ESP', '724', 'Spain', 'Espagne', 'EU', '34', 'EUR'),
    ('ET', 'ETH', '231', 'Ethiopia', 'Éthiopie', 'AF', '251', 'ETB'),
    ('FI', 'FIN', '246', 'Finland', 'Finlande', 'EU', '358', 'EUR'),
    ('FJ', 'FJI', '242', 'Fiji', 'Fidji', 'OC', '679', 'FJD'),
    ('FK', 'FLK', '238', 'Falkland Islands (Malvinas)', 'Îles Malouines', 'SA', '500', 'FKP'),
    ('FM', 'FSM', '583', 'Micronesia, Federated States of', 'Micronésie', 'OC', '691', 'USD'),
    ('FO', 'FRO', '234', 'Faroe Islands', 'Îles Féroé', 'EU', '298', 'DKK'),
    ('FR', 'FRA', '250', 'France', 'France', 'EU', '33', 'EUR'),
    ('GA', 'GAB', '266', 'Gabon', 'Gabon', 'AF', '241', 'XAF'),
    ('GB', 'GBR', '826', 'United Kingdom', 'Royaume-Uni', 'EU', '44', 'GBP'),
    ('GD', 'GRD', '308', 'Grenada', 'Grenade', 'NA', '1', 'XCD'),
    ('GE', 'GEO', '268', 'Georgia', 'Géorgie', 'AS', '995', 'GEL'),
    ('GF', 'GUF', '254', 'French Guiana', 'Guyane française', 'SA', '594', 'EUR'),
    ('GG', 'GGY', '831', 'Guernsey', 'Guernesey', 'EU', '44', 'GBP'),
    ('GH', 'GHA', '288', 'Ghana', 'Ghana', 'AF', '233', 'GHS'),
    ('GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', 'EU', '350', 'GIP'),
    ('GL', 'GRL', '304', 'Greenland', 'Groenland', 'NA', '299', 'DKK'),
    ('GM', 'GMB', '270', 'Republic of The Gambia', 'Gambie', 'AF', '220', 'GMD'),
    ('GN', 'GIN', '324', 'Guinea', 'Guinée', 'AF', '224', 'GNF'),
    ('GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'NA', '590', 'EUR'),
    ('GQ', 'GNQ', '226', 'Equatorial Guinea', 'Guinée équatoriale', 'AF', '240', 'XAF'),
    ('GR', 'GRC', '300', 'Greece', 'Grèce', 'EU', '30', 'EUR'),
    ('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'AN', '500', 'FKP'),
    ('GT', 'GTM', '320', 'Guatemala', 'Guatemala', 'NA', '502', 'GTQ'),
    ('GU', 'GUM', '316', 'Guam', 'Guam', 'OC', '1', 'USD'),
    ('GW', 'GNB', '624', 'Guinea-Bissau', 'Guinée-Bissau', 'AF', '245', 'XOF'),
    ('GY', 'GUY', '328', 'Guyana', 'Guyana', 'SA', '592', 'GYD'),
    ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong', 'AS', '852', 'HKD'),
    ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'Îles Heard-et-MacDonald', 'AN', '61', 'AUD'),
    ('HN', 'HND', '340', 'Honduras', 'Honduras', 'NA', '504', 'HNL'),
    ('HR', 'HRV', '191', 'Croatia', 'Croatie', 'EU', '385', 'EUR'),
    ('HT', 'HTI', '332', 'Haiti', 'Haïti', 'NA', '509', 'HTG'),
    ('HU', 'HUN', '348', 'Hungary', 'Hongrie', 'EU', '36', 'HUF'),
    ('ID', 'IDN', '360', 'Indonesia', 'Indonésie', 'AS', '62', 'IDR'),
    ('IE', 'IRL', '372', 'Ireland', 'Irlande', 'EU', '353', 'EUR'),
    ('IL', 'ISR', '376', 'Israel', 'Israël', 'AS', '972', 'ILS'),
    ('IM', 'IMN', '833', 'Isle of Man', 'Île de Man', 'EU', '44', 'GBP'),
    ('IN', 'IND', '356', 'India', 'Inde', 'AS', '91', 'INR'),
    ('IO', 'IOT', '086', 'British Indian Ocean Territory', 'Océan Indien Britannique', 'AS', '246', 'USD'),
    ('IQ', 'IRQ', '368', 'Iraq', 'Irak', 'AS', '964', 'IQD'),
    ('IR', 'IRN', '364', 'Islamic Republic of Iran', 'Iran', 'AS', '98', 'IRR'),
    ('IS', 'ISL', '352', 'Iceland', 'Islande', 'EU', '354', 'ISK'),
    ('IT', 'ITA', '380', 'Italy', 'Italie', 'EU', '39', 'EUR'),
    ('JE', 'JEY', '832', 'Jersey', 'Jersey', 'EU', '44', 'GBP'),
    ('JM', 'JAM', '388', 'Jamaica', 'Jamaïque', 'NA', '1', 'JMD'),
    ('JO', 'JOR', '400', 'Jordan', 'Jordanie', 'AS', '962', 'JOD'),
    ('JP', 'JPN', '392', 'Japan', 'Japon', 'AS', '81', 'JPY'),
    ('KE', 'KEN', '404', 'Kenya', 'Kenya', 'AF', '254', 'KES'),
    ('KG', 'KGZ', '417', 'Kyrgyzstan', 'Kirghizistan', 'AS', '996', 'KGS'),
    ('KH', 'KHM', '116', 'Cambodia', 'Cambodge', 'AS', '855', 'KHR'),
    ('KI', 'KIR', '296', 'Kiribati', 'Kiribati', 'OC', '686', 'AUD'),
    ('KM', 'COM', '174', 'Comoros', 'Comores', 'AF', '269', 'KMF'),
    ('KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Saint-Christophe-et-Niévès', 'NA', '1', 'XCD'),
    ('KP', 'PRK', '408', 'North Korea', 'Corée du Nord', 'AS', '850', 'KPW'),
    ('KR', 'KOR', '410', 'South Korea', 'Corée du Sud', 'AS', '82', 'KRW'),
    ('KW', 'KWT', '414', 'Kuwait', 'Koweït', 'AS', '965', 'KWD'),
    ('KY', 'CYM', '136', 'Cayman Islands', 'Îles Caïmans', 'NA', '1', 'KYD'),
    ('KZ', 'KAZ', '398', 'Kazakhstan', 'Kazakhstan', 'AS', '7', 'KZT'),
    ('LA', 'LAO', '418', 'Lao People''s Democratic Republic', 'Laos', 'AS', '856', 'LAK'),
    ('LB', 'LBN', '422', 'Lebanon', 'Liban', 'AS', '961', 'LBP'),
    ('LC', 'LCA', '662', 'Saint Lucia', 'Sainte-Lucie', 'NA', '1', 'XCD'),
    ('LI', 'LIE', '438', 'Liechtenstein', 'Liechtenstein', 'EU', '423', 'CHF'),
    ('LK', 'LKA', '144', 'Sri Lanka', 'Sri Lanka', 'AS', '94', 'LKR'),
    ('LR', 'LBR', '430', 'Liberia', 'Libéria', 'AF', '231', 'LRD'),
    ('LS', 'LSO', '426', 'Lesotho', 'Lesotho', 'AF', '266', 'LSL'),
    ('LT', 'LTU', '440', 'Lithuania', 'Lituanie', 'EU', '370', 'EUR'),
    ('LU', 'LUX', '442', 'Luxembourg', 'Luxembourg', 'EU', '352', 'EUR'),
    ('LV', 'LVA', '428', 'Latvia', 'Lettonie', 'EU', '371', 'EUR'),
    ('LY', 'LBY', '434', 'Libya', 'Libye', 'AF', '218', 'LYD'),
    ('MA', 'MAR', '504', 'Morocco', 'Maroc', 'AF', '212', 'MAD'),
    ('MC', 'MCO', '492', 'Monaco', 'Monaco', 'EU', '377', 'EUR'),
    ('MD', 'MDA', '498', 'Moldova, Republic of', 'Moldavie', 'EU', '373', 'MDL'),
    ('ME', 'MNE', '499', 'Montenegro', 'Monténégro', 'EU', '382', 'EUR'),
    ('MF', 'MAF', '663', 'Saint Martin (French part)', 'Saint-Martin (partie française)', 'NA', '590', 'EUR'),
    ('MG', 'MDG', '450', 'Madagascar', 'Madagascar', 'AF', '261', 'MGA'),
    ('MH', 'MHL', '584', 'Marshall Islands', 'Îles Marshall', 'OC', '692', 'USD'),
    ('MK', 'MKD', '807', 'The Republic of North Macedonia', 'Macédoine du Nord', 'EU', '389', 'MKD'),
    ('ML', 'MLI', '466', 'Mali', 'Mali', 'AF', '223', 'XOF'),
    ('MM', 'MMR', '104', 'Myanmar', 'Myanmar', 'AS', '95', 'MMK'),
    ('MN', 'MNG', '496', 'Mongolia', 'Mongolie', 'AS', '976', 'MNT'),
    ('MO', 'MAC', '446', 'Macao', 'Macao', 'AS', '853', 'MOP'),
    ('MP', 'MNP', '580', 'Northern Mariana Islands', 'Îles Mariannes du Nord', 'OC', '1', 'USD'),
    ('MQ', 'MTQ', '474', 'Martinique', 'Martinique', 'NA', '596', 'EUR'),
    ('MR', 'MRT', '478', 'Mauritania', 'Mauritanie', 'AF', '222', 'MRU'),
    ('MS', 'MSR', '500', 'Montserrat', 'Montserrat', 'NA', '1', 'XCD'),
    ('MT', 'MLT', '470', 'Malta', 'Malte', 'EU', '356', 'EUR'),
    ('MU', 'MUS', '480', 'Mauritius', 'Maurice', 'AF', '230', 'MUR'),
    ('MV', 'MDV', '462', 'Maldives', 'Maldives', 'AS', '960', 'MVR'),
    ('MW', 'MWI', '454', 'Malawi', 'Malawi', 'AF', '265', 'MWK'),
    ('MX', 'MEX', '484', 'Mexico', 'Mexique', 'NA', '52', 'MXN'),
    ('MY', 'MYS', '458', 'Malaysia', 'Malaisie', 'AS', '60', 'MYR'),
    ('MZ', 'MOZ', '508', 'Mozambique', 'Mozambique', 'AF', '258', 'MZN'),
    ('NA', 'NAM', '516', 'Namibia', 'Namibie', 'AF', '264', 'NAD'),
    ('NC', 'NCL', '540', 'New Caledonia', 'Nouvelle-Calédonie', 'OC', '687', 'XPF'),
    ('NE', 'NER', '562', 'Niger', 'Niger', 'AF', '227', 'XOF'),
    ('NF', 'NFK', '574', 'Norfolk Island', 'Île Norfolk', 'OC', '672', 'AUD'),
    ('NG', 'NGA', '566', 'Nigeria', 'Nigéria', 'AF', '234', 'NGN'),
    ('NI', 'NIC', '558', 'Nicaragua', 'Nicaragua', 'NA', '505', 'NIO'),
    ('NL', 'NLD', '528', 'Netherlands', 'Pays-Bas', 'EU', '31', 'EUR'),
    ('NO', 'NOR', '578', 'Norway', 'Norvège', 'EU', '47', 'NOK'),
    ('NP', 'NPL', '524', 'Nepal', 'Népal', 'AS', '977', 'NPR'),
    ('NR', 'NRU', '520', 'Nauru', 'Nauru', 'OC', '674', 'AUD'),
    ('NU', 'NIU', '570', 'Niue', 'Niué', 'OC', '683', 'NZD'),
    ('NZ', 'NZL', '554', 'New Zealand', 'Nouvelle-Zélande', 'OC', '64', 'NZD'),
    ('OM', 'OMN', '512', 'Oman', 'Oman', 'AS', '968', 'OMR'),
    ('PA', 'PAN', '591', 'Panama', 'Panama', 'NA', '507', 'PAB'),
    ('PE', 'PER', '604', 'Peru', 'Pérou', 'SA', '51', 'PEN'),
    ('PF', 'PYF', '258', 'French Polynesia', 'Polynésie française', 'OC', '689', 'XPF'),
    ('PG', 'PNG', '598', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'OC', '675', 'PGK'),
    ('PH', 'PHL', '608', 'Philippines', 'Philippines', 'AS', '63', 'PHP'),
    ('PK', 'PAK', '586', 'Pakistan', 'Pakistan', 'AS', '92', 'PKR'),
    ('PL', 'POL', '616', 'Poland', 'Pologne', 'EU', '48', 'PLN'),
    ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'NA', '508', 'EUR'),
    ('PN', 'PCN', '612', 'Pitcairn', 'Îles Pitcairn', 'OC', '64', 'NZD'),
    ('PR', 'PRI', '630', 'Puerto Rico', 'Porto Rico', 'NA', '1', 'USD'),
    ('PS', 'PSE', '275', 'State of Palestine', 'Palestine', 'AS', '970', 'ILS'),
    ('PT', 'PRT', '620', 'Portugal', 'Portugal', 'EU', '351', 'EUR'),
    ('PW', 'PLW', '585', 'Palau', 'Palaos', 'OC', '680', 'USD'),
    ('PY', 'PRY', '600', 'Paraguay', 'Paraguay', 'SA', '595', 'PYG'),
    ('QA', 'QAT', '634', 'Qatar', 'Qatar', 'AS', '974', 'QAR'),
    ('RE', 'REU', '638', 'Reunion', 'Réunion', 'AF', '262', 'EUR'),
    ('RO', 'ROU', '642', 'Romania', 'Roumanie', 'EU', '40', 'RON'),
    ('RS', 'SRB', '688', 'Serbia', 'Serbie', 'EU', '381', 'RSD'),
    ('RU', 'RUS', '643', 'Russian Federation', 'Russie', 'AS', '7', 'RUB'),
    ('RW', 'RWA', '646', 'Rwanda', 'Rwanda', 'AF', '250', 'RWF'),
    ('SA', 'SAU', '682', 'Saudi Arabia', 'Arabie Saoudite', 'AS', '966', 'SAR'),
    ('SB', 'SLB', '090', 'Solomon Islands', 'Îles Salomon', 'OC', '677', 'SBD'),
    ('SC', 'SYC', '690', 'Seychelles', 'Seychelles', 'AF', '248', 'SCR'),
    ('SD', 'SDN', '729', 'Sudan', 'Soudan', 'AF', '249', 'SDG'),
    ('SE', 'SWE', '752', 'Sweden', 'Suède', 'EU', '46', 'SEK'),
    ('SG', 'SGP', '702', 'Singapore', 'Singapour', 'AS', '65', 'SGD'),
    ('SH', 'SHN', '654', 'Saint Helena', 'Sainte-Hélène', 'AF', '290', 'SHP'),
    ('SI', 'SVN', '705', 'Slovenia', 'Slovénie', 'EU', '386', 'EUR'),
    ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard et Île Jan Mayen', 'EU', '47', 'NOK'),
    ('SK', 'SVK', '703', 'Slovakia', 'Slovaquie', 'EU', '421', 'EUR'),
    ('SL', 'SLE', '694', 'Sierra Leone', 'Sierra Leone', 'AF', '232', 'SLE'),
    ('SM', 'SMR', '674', 'San Marino', 'Saint-Marin', 'EU', '378', 'EUR'),
    ('SN', 'SEN', '686', 'Senegal', 'Sénégal', 'AF', '221', 'XOF'),
    ('SO', 'SOM', '706', 'Somalia', 'Somalie', 'AF', '252', 'SOS'),
    ('SR', 'SUR', '740', 'Suriname', 'Suriname', 'SA', '597', 'SRD'),
    ('SS', 'SSD', '728', 'South Sudan', 'Soudan du Sud', 'AF', '211', 'SSP'),
    ('ST', 'STP', '678', 'Sao Tome and Principe', 'São Tomé-et-Principe', 'AF', '239', 'STN'),
    ('SV', 'SLV', '222', 'El Salvador', 'El Salvador', 'NA', '503', 'USD'),
    ('SX', 'SXM', '534', 'Sint Maarten (Dutch part)', 'Saint-Martin (partie néerlandaise)', 'NA', '1', 'XCG'),
    ('SY', 'SYR', '760', 'Syrian Arab Republic', 'Syrie', 'AS', '963', 'SYP'),
    ('SZ', 'SWZ', '748', 'Eswatini', 'Royaume d''Eswatini', 'AF', '268', 'SZL'),
    ('TC', 'TCA', '796', 'Turks and Caicos Islands', 'Îles Turques-et-Caïques', 'NA', '1', 'USD'),
    ('TD', 'TCD', '148', 'Chad', 'Tchad', 'AF', '235', 'XAF'),
    ('TF', 'ATF', '260', 'French Southern Territories', 'Terres australes françaises', 'AN', '262', 'EUR'),
    ('TG', 'TGO', '768', 'Togo', 'Togo', 'AF', '228', 'XOF'),
    ('TH', 'THA', '764', 'Thailand', 'Thaïlande', 'AS', '66', 'THB'),
    ('TJ', 'TJK', '762', 'Tajikistan', 'Tadjikistan', 'AS', '992', 'TJS'),
    ('TK', 'TKL', '772', 'Tokelau', 'Tokelau', 'OC', '690', 'NZD'),
    ('TL', 'TLS', '626', 'Timor-Leste', 'Timor-Leste', 'OC', '670', 'USD'),
    ('TM', 'TKM', '795', 'Turkmenistan', 'Turkménistan', 'AS', '993', 'TMT'),
    ('TN', 'TUN', '788', 'Tunisia', 'Tunisie', 'AF', '216', 'TND'),
    ('TO', 'TON', '776', 'Tonga', 'Tonga', 'OC', '676', 'TOP'),
    ('TR', 'TUR', '792', 'Türkiye', 'Turquie', 'AS', '90', 'TRY'),
    ('TT', 'TTO', '780', 'Trinidad and Tobago', 'Trinité-et-Tobago', 'NA', '1', 'TTD'),
    ('TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', 'OC', '688', 'AUD'),
    ('TW', 'TWN', '158', 'Taiwan, Province of China', 'Taïwan', 'AS', '886', 'TWD'),
    ('TZ', 'TZA', '834', 'United Republic of Tanzania', 'République unie de Tanzanie', 'AF', '255', 'TZS'),
    ('UA', 'UKR', '804', 'Ukraine', 'Ukraine', 'EU', '380', 'UAH'),
    ('UG', 'UGA', '800', 'Uganda', 'Ouganda', 'AF', '256', 'UGX'),
    ('UM', 'UMI', '581', 'United States Minor Outlying Islands', 'Îles mineures éloignées des États-Unis', 'OC', '1', 'USD'),
    ('US', 'USA', '840', 'United States of America', 'États-Unis d''Amérique', 'NA', '1', 'USD'),
    ('UY', 'URY', '858', 'Uruguay', 'Uruguay', 'SA', '598', 'UYU'),
    ('UZ', 'UZB', '860', 'Uzbekistan', 'Ouzbékistan', 'AS', '998', 'UZS'),
    ('VA', 'VAT', '336', 'Holy See (Vatican City State)', 'Saint-Siège (Vatican)', 'EU', '39', 'EUR'),
    ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', 'NA', '1', 'XCD'),
    ('VE', 'VEN', '862', 'Venezuela', 'Venezuela', 'SA', '58', 'VES'),
    ('VG', 'VGB', '092', 'Virgin Islands, British', 'Îles vierges britanniques', 'NA', '1', 'USD'),
    ('VI', 'VIR', '850', 'Virgin Islands, U.S.', 'Îles vierges américaines', 'NA', '1', 'USD'),
    ('VN', 'VNM', '704', 'Vietnam', 'Vietnam', 'AS', '84', 'VND'),
    ('VU', 'VUT', '548', 'Vanuatu', 'Vanuatu', 'OC', '678', 'VUV'),
    ('WF', 'WLF', '876', 'Wallis and Futuna', 'Wallis-et-Futuna', 'OC', '681', 'XPF'),
    ('WS', 'WSM', '882', 'Samoa', 'Samoa', 'OC', '685', 'WST'),
    ('XK', 'XKK', '983', 'Kosovo', 'Kosovo', 'EU', '383', 'EUR'),
    ('YE', 'YEM', '887', 'Yemen', 'Yémen', 'AS', '967', 'YER'),
    ('YT', 'MYT', '175', 'Mayotte', 'Mayotte', 'AF', '262', 'EUR'),
    ('ZA', 'ZAF', '710', 'South Africa', 'Afrique du Sud', 'AF', '27', 'ZAR'),
    ('ZM', 'ZMB', '894', 'Zambia', 'Zambie', 'AF', '260', 'ZMW'),
    ('ZW', 'ZWE', '716', 'Zimbabwe', 'Zimbabwe', 'AF', '263', 'ZWG')
ON CONFLICT (alpha2) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_fr = EXCLUDED.name_fr,
    calling_code = EXCLUDED.calling_code,
    default_currency = EXCLUDED.default_currency
WHERE (ref.countries.name_en, ref.countries.name_fr, ref.countries.calling_code, ref.countries.default_currency)
      IS DISTINCT FROM (EXCLUDED.name_en, EXCLUDED.name_fr, EXCLUDED.calling_code, EXCLUDED.default_currency);
